import {
  Boxes,
  Braces,
  Cloud,
  Code2,
  Container,
  CreditCard,
  Database,
  DatabaseZap,
  GitBranch,
  Globe,
  Layers,
  Monitor,
  Network,
  Palette,
  Radio,
  Rocket,
  Server,
  ShieldCheck,
  Sparkles,
  TestTubeDiagonal,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the `icon` keys used in the JSON data to icon components.
 * Add a new entry here to support a new key; unknown keys fall back to `Code2`.
 */
const iconMap: Record<string, LucideIcon> = {
  csharp: Braces,
  dotnet: Layers,
  aspnet: Server,
  desktop: Monitor,
  jwt: ShieldCheck,
  oauth: ShieldCheck,
  identity: ShieldCheck,
  signalr: Radio,
  linq: Database,
  swagger: Sparkles,
  testing: TestTubeDiagonal,
  html: Code2,
  css: Palette,
  javascript: Braces,
  typescript: Layers,
  react: Layers,
  nextjs: Globe,
  tailwind: Palette,
  bootstrap: Boxes,
  sass: Palette,
  jquery: Code2,
  ajax: Network,
  json: Braces,
  api: Network,
  websocket: Radio,
  sqlserver: Database,
  database: DatabaseZap,
  stripe: CreditCard,
  paypal: CreditCard,
  webhook: Webhook,
  aws: Cloud,
  azure: Cloud,
  docker: Container,
  git: GitBranch,
  workflow: Workflow,
  code: Code2,
  layers: Layers,
  shield: ShieldCheck,
  globe: Globe,
  rocket: Rocket,
  zap: Zap,
  boxes: Boxes,
};

export function resolveIcon(key: string): LucideIcon {
  return iconMap[key.toLowerCase()] ?? Code2;
}
